# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec402d6e93ada1b847aef1f0fd8bbfd4f593e7f0393d9bcc3891accb3eb6bd8716bb13eac9d6431cf52abda5a368936daff610a9a304ce755b5e849e68ecea04

test:
  secret_key_base: 446937ceecb378c1908061d01a62fe25acdcd49c84e84026013259f295d51d30cf15af5686d07156a9647104fd7c8f006f09fbd996242757487b01e19b408773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
